/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./*.html", "./src/**/*.{js,jsx,ts,tsx}"], 
    theme: {
        extend: {
            colors: {
                "on-error": "#690005",
                "on-surface": "#e2e2e2",
                "primary-container": "#10b981",
                "primary-fixed": "#6ffbbe",
                "on-primary-fixed-variant": "#005236",
                "error": "#ffb4ab",
                "on-secondary-container": "#00424e",
                "surface-container-highest": "#353535",
                "on-surface-variant": "#bbcabf",
                "inverse-surface": "#e2e2e2",
                "on-secondary": "#003640",
                "surface-container-lowest": "#0e0e0e",
                "tertiary": "#c3c7cd",
                "inverse-on-surface": "#303030",
                "primary-fixed-dim": "#4edea3",
                "on-primary-container": "#00422b",
                "tertiary-container": "#9fa3a9",
                "on-secondary-fixed": "#001f26",
                "on-secondary-fixed-variant": "#004e5c",
                "on-tertiary-fixed": "#171c20",
                "on-tertiary-container": "#353a3e",
                "surface": "#131313",
                "secondary-fixed": "#acedff",
                "secondary-fixed-dim": "#4cd7f6",
                "surface-container-low": "#1b1b1b",
                "secondary-container": "#03b5d3",
                "surface-tint": "#4edea3",
                "outline": "#86948a",
                "inverse-primary": "#006c49",
                "surface-variant": "#353535",
                "tertiary-fixed": "#dfe3e9",
                "outline-variant": "#3c4a42",
                "on-background": "#e2e2e2",
                "secondary": "#4cd7f6",
                "error-container": "#93000a",
                "on-tertiary": "#2c3136",
                "surface-dim": "#131313",
                "tertiary-fixed-dim": "#c3c7cd",
                "primary": "#4edea3",
                "surface-container": "#1f1f1f",
                "background": "#131313",
                "on-error-container": "#ffdad6",
                "on-primary": "#003824",
                "surface-bright": "#393939",
                "on-primary-fixed": "#002113",
                "surface-container-high": "#2a2a2a",
                "on-tertiary-fixed-variant": "#43474c"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
}